/* Generated by Preqorsor 1.14.0 (git sha1 9b93f695a, ccache c++ 17.0.0 -fPIC -O3) */

(* leakage_power_unit = "1nW" *)
(* LeakagePower = "1.0" *)
(* area = "1.0" *)
(* memory =  1  *)
(* blackbox =  1  *)
module myram(CLK, DI, DO);
  input CLK;
  wire CLK;
  input [49:0] DI;
  wire [49:0] DI;
  output [49:0] DO;
  wire [49:0] DO;
endmodule
