/* Generated by Preqorsor 1.0.1 (git sha1 a48727a53, ccache c++ 15.0.0 -fPIC -O3) */

(* leakage_power_unit = "1pW" *)
(* LeakagePower = "0" *)
(* area = "2" *)
(* stdcell =  1  *)
(* blackbox =  1  *)
module AN2(A, B, Z, D, E);
  input A;
  wire A;
  input B;
  wire B;
  output Z;
  wire Z;
  input [15:30] D;
  wire [15:30] D;
  input [0:31] E;
  wire [0:31] E;
endmodule

(* leakage_power_unit = "1pW" *)
(* LeakagePower = "0" *)
(* area = "2" *)
(* stdcell =  1  *)
(* blackbox =  1  *)
module OR2(A, B, Z);
  input A;
  wire A;
  input B;
  wire B;
  output Z;
  wire Z;
endmodule
