/* Generated by Preqorsor 1.0.1 (git sha1 a48727a53, ccache c++ 15.0.0 -fPIC -O3) */

(* leakage_power_unit = "1pW" *)
(* LeakagePower = "0" *)
(* area = "0" *)
(* stdcell =  1  *)
(* blackbox =  1  *)
module ex(A);
  input [0:3] A;
  wire [0:3] A;
endmodule
