/* Generated by Preqorsor 0.48.8 (git sha1 be77aad82, ccache c++ 15.0.0 -fPIC -O3) */

(* leakage_power_unit = "1pW" *)
(* LeakagePower = "0" *)
(* area = "0.26244" *)
(* blackbox =  1  *)
module ICGx1_ASAP7_75t_L(GCLK, CLK, ENA, SE);
  input CLK;
  wire CLK;
  input ENA;
  wire ENA;
  output GCLK;
  wire GCLK;
  input SE;
  wire SE;
endmodule
